<a href="https://colab.research.google.com/github/danghuy11/OAI/blob/main/01-convolution/convolution5-mlps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

In [2]:
# Prepare samples
samples_inp = torch.tensor([[0.1,0.2,0.3],[0.1,0.1,0.1],[0.4,0.4,0.4],[0.9,0.9,0.9],[0.3,0.2,0.1],[0.0,0.0,0.1],[0.0,0.0,0.0]],dtype=torch.float)
samples_out = torch.tensor([[0.123],[0.111],[0.444],[0.999],[0.321],[0.001],[0.0]],dtype=torch.float)

In [3]:
# ==================================== PERCEPTRON ====================================

In [4]:
class Perceptron(nn.Module):
    # initialization
    def __init__(self, num_inputs, num_hiddens, num_outputs):
        super().__init__()
        self.layer1 = nn.Linear(num_inputs, num_hiddens)
        self.layer2 = nn.Linear(num_hiddens, num_outputs)
    # forward
    def forward(self, x):
        return self.layer2(self.layer1(x))

In [5]:
# Define model
model = Perceptron(3,10,1)

In [6]:
# Define loss function
loss_function = nn.MSELoss(reduction='sum')

In [7]:
# Define optimizer
optimizer = optim.Adam(model.parameters())

In [8]:
# Training
num_epochs = 8000
for t in range(num_epochs):

    # Forward pass
    out = model(samples_inp)
    loss = loss_function(out, samples_out)
    if t % 10 == 0:
        print(t, loss.item())

    # Reset gradients
    optimizer.zero_grad()

    # Backward pass
    loss.backward()

    # Update model parameters (weights)
    optimizer.step()

0 0.3291260004043579
10 0.2650560736656189
20 0.2091798484325409
30 0.16196435689926147
40 0.12297190725803375
50 0.09161844849586487
60 0.06737185269594193
70 0.04962228983640671
80 0.037510138005018234
90 0.029897036030888557
100 0.025495808571577072
110 0.023091880604624748
120 0.021740151569247246
130 0.02084166929125786
140 0.020093752071261406
150 0.01937948167324066
160 0.018668491393327713
170 0.01795869879424572
180 0.017252963036298752
190 0.01655331440269947
200 0.01586099900305271
210 0.015177012421190739
220 0.014502334408462048
230 0.013838003389537334
240 0.013184941373765469
250 0.012544042430818081
260 0.011916086077690125
270 0.011301870457828045
280 0.010702090337872505
290 0.01011739857494831
300 0.009548427537083626
310 0.00899573415517807
320 0.008459855802357197
330 0.0079412292689085
340 0.0074403127655386925
350 0.0069574457593262196
360 0.0064929635263979435
370 0.006047103554010391
380 0.005620072595775127
390 0.005211997777223587
400 0.004822965711355209
410

In [9]:
# Print weighs
for param in model.parameters():
    print(param.data)

tensor([[ 0.2967, -0.4487,  0.1635],
        [-0.4348, -0.4178, -0.1971],
        [ 0.2499,  0.5050,  0.0341],
        [ 0.6837, -0.4158,  0.0144],
        [-0.0797, -0.0069, -0.5820],
        [-0.7344,  0.4345,  0.0529],
        [-0.1618, -0.1160, -0.3091],
        [ 0.6045,  0.4564, -0.6636],
        [-0.2677, -0.0420,  0.4929],
        [ 0.1609,  0.0695, -0.3761]])
tensor([-0.0919,  0.2177,  0.3485,  0.0817,  0.2501, -0.0768, -0.5028, -0.4130,
        -0.0422,  0.0116])
tensor([[ 0.0088, -0.2877,  0.4050,  0.1540, -0.2626, -0.6188, -0.1578,  0.1724,
         -0.1752,  0.0859]])
tensor([-0.0886])


In [10]:
# Test
result = model(torch.tensor([[0.7,0.8,0.9]],dtype=torch.float))
print('test result',round(result[0].item(),3))

test result 0.789


In [11]:
# ================ PERCEPTRONS RUNNING IN PARALLEL AND SHARING WEIGHTS ================

In [12]:
samples_inp = samples_inp.unsqueeze(-1).unsqueeze(-1)
samples_out = samples_out.unsqueeze(-1).unsqueeze(-1)

In [13]:
class FCPerceptron(nn.Module):
    # initialization
    def __init__(self, num_inputs, num_hiddens, num_outputs):
        super().__init__()
        self.layer1 = nn.Conv2d(num_inputs, num_hiddens, (1,1))
        self.layer2 = nn.Conv2d(num_hiddens, num_outputs, (1,1))
    # forward
    def forward(self, x):
        return self.layer2(self.layer1(x))

In [14]:
# Define model
model = FCPerceptron(3,10,1)

In [15]:
# Define loss function
loss_function = nn.MSELoss(reduction='sum')

In [16]:
# Define optimizer
optimizer = optim.Adam(model.parameters())

In [17]:
# Training
num_epochs = 8000
for t in range(num_epochs):

    # Forward pass
    out = model(samples_inp)
    loss = loss_function(out, samples_out)
    if t % 10 == 0:
        print(t, loss.item())

    # Reset gradients
    optimizer.zero_grad()

    # Backward pass
    loss.backward()

    # Update model parameters (weights)
    optimizer.step()

0 0.9308277368545532
10 0.8020539879798889
20 0.6923585534095764
30 0.5878645181655884
40 0.49160006642341614
50 0.40420347452163696
60 0.32626843452453613
70 0.25833019614219666
80 0.20070169866085052
90 0.15341401100158691
100 0.11609362065792084
110 0.08793599158525467
120 0.0677507072687149
130 0.05407322198152542
140 0.04534146562218666
150 0.040083903819322586
160 0.03706800565123558
170 0.035373181104660034
180 0.03438543528318405
190 0.033738795667886734
200 0.033238381147384644
210 0.03279181197285652
220 0.032360468059778214
230 0.031930483877658844
240 0.03149786964058876
250 0.03106200508773327
260 0.030623162165284157
270 0.0301817674189806
280 0.029738228768110275
290 0.029292898252606392
300 0.028846127912402153
310 0.028398236259818077
320 0.02794954553246498
330 0.02750033512711525
340 0.027050893753767014
350 0.026601484045386314
360 0.02615235187113285
370 0.02570374682545662
380 0.025255894288420677
390 0.02480900287628174
400 0.024363307282328606
410 0.023918967694

In [18]:
# Print weighs
for param in model.parameters():
    print(param.data)

tensor([[[[-0.1922]],

         [[-0.3644]],

         [[ 0.4131]]],


        [[[-0.4354]],

         [[-0.5023]],

         [[ 0.4935]]],


        [[[ 0.6472]],

         [[ 0.0639]],

         [[-0.2297]]],


        [[[ 0.5756]],

         [[-0.0389]],

         [[-0.0157]]],


        [[[-0.1107]],

         [[-0.5452]],

         [[-0.4717]]],


        [[[ 0.3639]],

         [[-0.4184]],

         [[ 0.3935]]],


        [[[-0.8648]],

         [[-0.1637]],

         [[-0.3815]]],


        [[[-0.2455]],

         [[-0.0996]],

         [[ 0.0188]]],


        [[[ 0.0497]],

         [[-0.5321]],

         [[-0.2537]]],


        [[[ 0.0262]],

         [[-0.2517]],

         [[ 0.5684]]]])
tensor([ 0.0330,  0.3805, -0.2292,  0.0980,  0.2434,  0.0991, -0.0014,  0.5445,
         0.5520, -0.0111])
tensor([[[[ 0.0297]],

         [[-0.3455]],

         [[ 0.2845]],

         [[ 0.4025]],

         [[-0.1914]],

         [[ 0.5021]],

         [[-0.1952]],

         [[-0.2664]],



In [19]:
# Test
result = model(torch.tensor([[[[0.7]],[[0.8]],[[0.9]]]],dtype=torch.float))
print('test result',round(result[0].item(),3))

test result 0.789


In [20]:
# Run in parallel 3 x 3 perceptrons that share weights
data = torch.tensor([[[[0.7,0.8,0.9],[0.4,0.5,0.6],[0.1,0.2,0.3]],[[0.7,0.8,0.8],[0.4,0.5,0.5],[0.1,0.2,0.2]],[[0.7,0.8,0.1],[0.4,0.4,0.4],[0.1,0.2,0.1]]]],dtype=torch.float)
result = model(data.permute(0,3,1,2))
import numpy as np
print('test result:\n',np.round(result[0].detach().cpu().numpy(),3))

test result:
 [[[0.789 0.456 0.123]
  [0.788 0.455 0.122]
  [0.781 0.444 0.121]]]
